### ISSUE TITLE
PyInstaller builds crashes on start in Windows

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-qt#16]
```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 46, in <module>
  File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 573, in load_module
ImportError: DLL load failed: Det går inte att hitta den angivna proceduren.
Failed to execute script pyi_rth_qt5plugins
```

Seems related to this: https://github.com/pyinstaller/pyinstaller/issues/2152

Attempting a fix in: https://github.com/ActivityWatch/aw-qt/commit/597fdf1a225fc9abd7c0c910eb9354e244de0f84

**Comment by ErikBjare** [comment]
So the fix I tried above didn't quite work. With the help of my new Windows VM however, I managed to get this PR together that builds as it should on my machine: https://github.com/ActivityWatch/aw-qt/pull/17

**Comment by ErikBjare** [comment]
The PR was merged, now I'm just going to update the subrepo in the bundle and ensure the warnings are gone on Appveyor.

**Comment by ErikBjare** [comment]
Build is running: https://ci.appveyor.com/project/ErikBjare/activitywatch/build/1.0.252

**Comment by ErikBjare** [comment]
Warnings are gone, closing.
