### ISSUE TITLE
Crashes when pressing "Open Log Folder"

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-qt#18]
```
Traceback (most recent call last):
  File "/home/johan/Programming/activitywatch/aw-qt/aw_qt/trayicon.py", line 78, in <lambda>
    menu.addAction("Open log folder", lambda: open_dir(aw_core.dirs.get_log_dir()))
  File "/home/johan/Programming/activitywatch/aw-core/aw_core/dirs.py", line 10, in wrapper
    path = f(*args, **kwargs)
TypeError: get_log_dir() missing 1 required positional argument: 'module_name'
zsh: abort (core dumped)  aw-qt
```

**Comment by ErikBjare** [comment]
Should probably make it accept `None` as a valid module_name for when we want to get the root log folder.

**Comment by ErikBjare** [comment]
Should be fixed in https://github.com/ActivityWatch/aw-core/pull/40
